"""Part 2 self-preference page for the v3 corpus (docs/v3/selfpref.html).

Reads docs/analysis/selfpref_v3.json (scripts/selfpref_analysis.py) and the
figures from scripts/selfpref_figures.py. Every one of the 42 arms judged every
express-yourself piece, self included; the page reports leniency-corrected
self-preference (strict self, ±thinking sibling, family), the thinking-on/off
contrast, the competence gate, the judge × author matrix, and methods.
"""
from __future__ import annotations

import html as _h
import json
import re
from pathlib import Path
from statistics import mean

from .report_common import cell, details_section, fnote, heat, page, scorebar, table

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
FIG = "../analysis"
CSS = (".chart img { width: 100%; border: 1px solid var(--border); border-radius: 8px; }"
       " .chart { margin: 1rem 0 1.5rem; } .chart figcaption { color: var(--muted); font-size: .85rem; margin-top: .4rem; }"
       " table.matrix th.rot { writing-mode: vertical-rl; transform: rotate(180deg); font-weight: 400; font-size: .75rem; padding: 4px 2px; }"
       " table.matrix td { font-size: .72rem; padding: 2px 4px; text-align: center; }"
       " table.matrix td.diag { outline: 2px solid var(--fg); outline-offset: -2px; font-weight: 600; }")


def _fig(name, caption):
    return (f"<figure class='chart'><img src='{FIG}/{name}' alt='{_h.escape(caption)}'>"
            f"<figcaption>{caption}</figcaption></figure>")


def _ci(s):
    return f"[{s['ci95'][0]:+.2f}, {s['ci95'][1]:+.2f}]" + ("&nbsp;*" if s["ci95"][0] > 0 or s["ci95"][1] < 0 else "")


def _corr(s):
    return heat(s["corrected"], 0.5) if s else "<td>—</td>"


def _pill_row(active_v3: bool):
    a = ("<a href='{h}' style=\"font-size:.85rem;padding:4px 13px;border-radius:7px;"
         "border:1px solid #cbb99a;background:#fff;color:var(--fg);text-decoration:none;font-weight:400\">{t}</a>")
    on = ("<span style=\"font-size:.85rem;padding:4px 13px;border-radius:7px;"
          "border:1px solid var(--accent);background:var(--accent);color:var(--bg);font-weight:400\">{t}</span>")
    v1 = "v1/v2 — style space &amp; taste"
    v3 = "v3 — 42 arms × 1,611 pieces, every model judges every piece"
    items = ((on.format(t=v1) if not active_v3 else a.format(h="../selfpref.html", t=v1))
             + (on.format(t=v3) if active_v3 else a.format(h="v3/selfpref.html", t=v3)))
    return ("<div id='corpus-toggle' style='max-width:980px;margin:.9rem auto -1.1rem;padding:0 1.25rem;"
            "display:flex;gap:8px;align-items:center;flex-wrap:wrap'>"
            "<span style='font-weight:600;font-size:.9rem;color:var(--fg)'>Corpus</span>" + items + "</div>")


def build(analysis: Path | None = None) -> Path:
    analysis = analysis or DOCS_DIR / "analysis"
    D = json.loads((analysis / "selfpref_v3.json").read_text(encoding="utf-8"))
    S, J, ORDER = D["summary"], D["judges"], D["judges_order"]
    sig_pos, sig_neg = S["n_positive_strict_self"], S["n_negative_strict_self"]
    t = S["thinking_minus_base_strict_self"]

    scope = (f"<h1>Self-preference <span class='sub'>v3 corpus · {S['n_judges']} judges × {S['n_pieces']:,} pieces · "
             f"{S['n_verdicts']:,} verdicts</span></h1>"
             "<p class='scope'>Do LLMs like their own music? Every one of the 42 v3 arms (21 models, each with and without "
             "thinking) judged every express-yourself piece — ABC and code-gen — on the blind rubric"
             f"{fnote('llm-judge')}, <b>including its own</b>. A judge's <i>self-preference</i> is how much higher it scores "
             "its own pieces than the rest of the panel does, minus how much higher it scores <i>everyone's</i> pieces "
             "(its leniency). Positive = favors its own work beyond its general generosity; negative = harsher on itself. "
             "Quality = mean of the eight craft dimensions. Generated by <code>llm-music selfpref-v3-report</code>.</p>")

    headline = (f"<p><b>Most models do not reliably favor their own music, but a distinct minority do — strongly.</b> "
                f"Across 42 judge arms the mean corrected self-preference is {S['mean_corrected_strict_self']:+.2f} points on the 1–5 scale; "
                f"{sig_pos} arms are significantly self-favoring and {sig_neg} significantly self-critical (95% bootstrap CIs over pieces). "
                f"The self-favoring cluster is dominated by Gemini and Grok thinking arms (gemini-3.7-flash-thinking and grok-4.3-thinking both "
                f"≈ +0.65, half a rubric point); the gpt-5.x thinking arms sit at the other end (gpt-5.6-thinking {J['gpt-5.6-thinking']['strict_self']['corrected']:+.2f}), "
                f"and the Anthropic arms cluster near zero. Self-preference tracks judge <i>incompetence</i>: judges whose scores agree "
                f"less with the rest of the panel favor themselves more (r = {S['competence_vs_selfbias_r']:+.2f}). Turning thinking on "
                f"shifts self-preference by only {t['mean']:+.2f} on average across the {t['n_families']} families, but the effect is "
                f"wildly heterogeneous — it widens the gap for some families and narrows it for others — while a family's base and thinking "
                f"arms still resemble each other (r = {S['base_vs_thinking_selfbias_r']:+.2f}).</p>")

    # ---- 1. per-judge table ----
    rows = []
    for j in sorted(ORDER, key=lambda x: -(J[x]["strict_self"] or {"corrected": -9})["corrected"]):
        r = J[j]; s = r["strict_self"]
        if not s:
            continue
        rows.append([j, cell(s["n_self"], "int"), cell(s["raw_gap"], "f2"), cell(s["leniency"], "f2"),
                     _corr(s), _ci(s), _corr(r["sibling"]), _corr(r["family_self"]),
                     _corr(r["by_mode"]["abc"]), _corr(r["by_mode"]["codegen"]),
                     cell(r["competence_r"], "f2"), cell(r["mean_given"], "f2")])
    cols = [("judge", None), ("n own", "own pieces judged"),
            ("raw gap", "mean of (own score − panel mean) on its OWN pieces"),
            ("leniency", "the same gap on OTHER families' pieces — how generous the judge is in general"),
            ("self", "corrected self-preference = raw gap − leniency (strict: the same arm's pieces)"),
            ("95% CI", "bootstrap over pieces; * = excludes zero"),
            ("sibling", "the ±thinking sibling arm's pieces, same correction"),
            ("family", "own + sibling pieces pooled"),
            ("ABC", "self-preference on ABC pieces only"), ("code-gen", "self-preference on code-gen pieces only"),
            ("competence", "r(judge's score, leave-one-out panel mean) across all pieces"),
            ("mean given", "the judge's average quality score — its severity")]
    sec1 = ("<h2>Does a model rate its own music higher than the panel does?</h2>"
            "<p class='scope'>Sorted by corrected self-preference. Green favors self, red penalizes self; the sibling and "
            "family columns test whether the effect extends to the same model run with thinking flipped.</p>"
            + _fig("selfpref_bias.png", "Leniency-corrected self-preference per judge arm with 95% bootstrap CIs.")
            + table(cols, rows))

    # ---- 2. thinking vs base ----
    fam = {}
    for j in ORDER:
        s = J[j]["strict_self"]
        if s:
            fam.setdefault(J[j]["family"], {})["thinking" if J[j]["thinking"] else "base"] = s["corrected"]
    frows = [[f, heat(v["base"], 0.5), heat(v["thinking"], 0.5), heat(v["thinking"] - v["base"], 0.5)]
             for f, v in sorted(fam.items(), key=lambda kv: -(kv[1].get("thinking", 0) - kv[1].get("base", 0)))
             if "base" in v and "thinking" in v]
    sec2 = ("<h2>Thinking on vs off <span class='sub'>(same model, both arms)</span></h2>"
            f"<p class='scope'>Mean change {t['mean']:+.2f} across {t['n_families']} families — small on average, large in "
            "either direction for individual families. Base and thinking arms of a family correlate at r = "
            f"{S['base_vs_thinking_selfbias_r']:+.2f}: self-preference is mostly a property of the model, modulated by reasoning.</p>"
            + _fig("selfpref_thinking.png", "Corrected self-preference of each family's base arm (light) and thinking arm (dark).")
            + table([("family", None), ("base", "corrected self-preference, base arm"),
                     ("thinking", "corrected self-preference, thinking arm"), ("Δ", "thinking − base")], frows))

    # ---- 3. competence ----
    low = S["low_competence_judges"]
    sec3 = ("<h2>Self-preference and judge competence</h2>"
            f"<p class='scope'>Competence is how well a judge's scores track the rest of the panel (leave-one-out r). "
            f"It correlates with self-preference at r = {S['competence_vs_selfbias_r']:+.2f}: the judges that agree least with everyone else "
            f"are the ones that like themselves most. Leniency correlates at r = {S['leniency_vs_selfbias_r']:+.2f}; how good a model's "
            f"own pieces are (panel mean) at r = {S['own_quality_vs_selfbias_r']:+.2f} — self-preference is not just "
            "strong composers correctly recognizing strong work. Judges below r = 0.75: "
            + ", ".join(f"{k} ({v:.2f})" for k, v in low.items()) + ".</p>"
            + _fig("selfpref_competence.png", "Each dot is one judge arm; extremes labelled."))

    # ---- 4. judge x author matrix (deviation from the judge's row mean) ----
    M = D["matrix"]
    def short(a):
        return a.replace("-thinking", "†").replace("gemini-", "gem").replace("sonnet-", "son").replace("fable-", "fab")
    hdr = "<tr><th class='m'>judge ↓ / author →</th>" + "".join(f"<th class='rot'>{short(a)}</th>" for a in ORDER) + "</tr>"
    body_rows = []
    for j in ORDER:
        rowmean = mean(M[j].values())
        tds = []
        for a in ORDER:
            v = M[j].get(a)
            if v is None:
                tds.append("<td>—</td>"); continue
            td = heat(v - rowmean, 0.6)
            if a == j:
                td = td.replace("<td ", "<td class='diag' ", 1)
            tds.append(td)
        body_rows.append(f"<tr><td class='m'>{j}</td>{''.join(tds)}</tr>")
    sec4 = ("<h2>Judge × author matrix <span class='sub'>(deviation from each judge's own mean)</span></h2>"
            "<p class='scope'>Rows are judges, columns are composers, cells are the judge's mean quality score for that "
            "composer's pieces minus the judge's overall mean (so leniency is removed). † = thinking arm. The outlined "
            "diagonal is each judge on its own pieces; a green diagonal cell is self-favoring.</p>"
            f"<div class='tscroll'><table class='matrix'>{hdr}{''.join(body_rows)}</table></div>")

    # ---- 5. composer leaderboard ----
    AQ = D["author_quality"]
    lrows = [[a, scorebar(AQ[a]), cell(J[a]["strict_self"]["n_self"] if J.get(a, {}).get("strict_self") else None, "int")]
             for a in sorted(AQ, key=lambda x: -AQ[x])]
    sec5 = ("<h2>Composer leaderboard <span class='sub'>(42-judge panel mean, self included)</span></h2>"
            "<p class='scope'>Mean quality of each arm's pieces across the whole panel — the denominator the self-preference "
            "numbers are measured against.</p>"
            + table([("composer", None), ("panel mean quality", "mean of the 8 craft dimensions, averaged over all 42 judges and the arm's pieces"),
                     ("pieces", "express-yourself pieces that generated successfully")], lrows))

    methods = details_section(
        "Methods, coverage and caveats",
        "<ul>"
        "<li><b>Data.</b> The v3 express-yourself prompt only: 840 ABC pieces (42 arms × 20) and 771 code-gen pieces "
        "(69 code-gen generations failed and never existed). Each piece was judged by all 42 arms with the v3 judge prompt "
        f"(blind, titles/notes stripped): {S['n_verdicts']:,} of {S['n_pieces'] * S['n_judges']:,} verdicts (3 missing — two Fable arms returned no "
        "parseable JSON three times on one opus-4.1-thinking piece).</li>"
        "<li><b>Estimator.</b> For judge J on piece i, gap = q<sub>J</sub>(i) − mean of the other 41 judges on i, with q the mean of the "
        "eight craft dimensions. Leniency = mean gap over pieces by other families; strict self = mean gap over J's own pieces − leniency; "
        "sibling and family analogously. CIs: 1,000 bootstrap resamples of pieces (self set and leniency set resampled independently). "
        "This is the within-piece paired form of the leniency correction (score minus what the same piece got from everyone else), "
        "which controls for piece-mix difficulty — a judge whose own pieces happen to be good is not credited for it.</li>"
        "<li><b>Provenance.</b> Anthropic-native, Gemini and kimi-k3 arms were judged through provider batch APIs, the rest realtime, all "
        "with byte-identical prompts. Gemini batches ran with the JSON response-format hint omitted (Google's batch service otherwise "
        "flattens nested JSON); every batch was validated on a 50-piece slice against the Anthropic panel before scaling, and every full "
        "batch re-checked before merging.</li>"
        "<li><b>Caveats.</b> Self-preference here is behavioral: it does not distinguish a model recognizing its own style from a model "
        "simply liking the style it also produces (the v1/v2 style-space page tackles that with taste vectors and matched lookalikes). "
        "Cross-family agreement is lower for some families (Gemini ≈ 0.6 vs Anthropic ≈ 0.9), so competence and self-preference are "
        "partly family effects. Emotion labels and reasoning traces are in the raw file but not analyzed here.</li></ul>")

    body = scope + headline + sec1 + sec2 + sec3 + sec4 + sec5 + methods
    html_text = page("Self-preference — v3 corpus", "selfpref.html", body, extra_css=CSS)
    html_text = re.sub(r'(<a href=")(?!https?|\.\./|#)', r"\1../", html_text)
    html_text = re.sub(r'(<link[^>]*href=")(?!https?|\.\./)', r"\1../", html_text)
    html_text = html_text.replace("</nav>", "</nav>" + _pill_row(True), 1)
    out = DOCS_DIR / "v3" / "selfpref.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html_text, encoding="utf-8")
    # back-patch the v1/v2 page with a corpus pill row (idempotent)
    v1 = DOCS_DIR / "selfpref.html"
    if v1.exists() and "v3/selfpref.html" not in v1.read_text(encoding="utf-8"):
        txt = v1.read_text(encoding="utf-8").replace("</nav>", "</nav>" + _pill_row(False), 1)
        v1.write_text(txt, encoding="utf-8")
    return out


if __name__ == "__main__":
    print(build())
