#!/usr/bin/env python3
"""Build the matching-program section of docs/multimodal.html — faithfulness
of claims, the text-informativeness ladder (foil / title / short / full
description), within-composer matching, and the self-recognition
difference-in-differences with a permutation test. All numbers are computed
here from the raw docs/analysis artifacts and spliced into multimodal.html
between BEGIN/END matching-program markers (idempotent — safe to re-run).

    python scripts/build_descriptions_page.py
"""

from __future__ import annotations

import html
import json
import random
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "docs/analysis"
OUT = ROOT / "docs/multimodal.html"
MARK_BEGIN = "<!-- BEGIN matching-program (generated by scripts/build_descriptions_page.py) -->"
MARK_END = "<!-- END matching-program -->"
SEED = 20260723
N_PERM = 2000

JUDGES = ["fable-5", "gpt-5.5", "opus-4.8-thinking", "gemini-2.5-pro",
          "deepseek-v4-pro", "opus-4.8", "sonnet-4.6", "grok-4.3", "gpt-4.1",
          "qwen3-max", "llama-4-maverick"]


def load(tag):
    return json.loads((ANALYSIS / f"description_matching{tag}.json").read_text())


def acc_map(recs, method):
    per = defaultdict(list)
    for r in recs:
        if r["method"] != method:
            continue
        for x in r["results"]:
            per[r["judge"]].append(x["correct"])
    return {j: sum(v) / len(v) for j, v in per.items()}


def pooled(recs, method):
    v = [x["correct"] for r in recs if r["method"] == method
         for x in r["results"]]
    return sum(v) / len(v)


def cells_of(recs):
    cells = defaultdict(list)
    for r in recs:
        owner = str(r["round"]).split("#")[0]
        for x in r["results"]:
            cells[(r["judge"], owner)].append(x["correct"])
    return cells


def did_rows(cells):
    """Per-composer self-recognition DiD (controls judge ability AND puzzle
    difficulty), plus the mean under a given composer->author assignment."""
    judges = sorted({j for j, _ in cells})

    def one(J, C):
        a = sum(cells[(J, C)]) / len(cells[(J, C)])
        b_v = [x for (j, o), vs in cells.items() if j == J and o != C for x in vs]
        c_v = [x for (j, o), vs in cells.items() if j != J and o == C for x in vs]
        d_v = [x for (j, o), vs in cells.items() if j != J and o != C and j != o
               for x in vs]
        b, c, d = (sum(v) / len(v) for v in (b_v, c_v, d_v))
        return a, b, c, d, (a - b) - (c - d)

    rows = {C: one(C, C) for C in judges if (C, C) in cells}

    def mean_for(assign):
        vals = []
        for C, J in assign.items():
            if (J, C) in cells:
                vals.append(one(J, C)[4])
        return sum(vals) / len(vals)

    obs = mean_for({c: c for c in rows})
    rng = random.Random(SEED)
    hits = 0
    for _ in range(N_PERM):
        perm = {c: rng.choice([j for j in judges if (j, c) in cells])
                for c in rows}
        if mean_for(perm) >= obs:
            hits += 1
    return rows, obs, (hits + 1) / (N_PERM + 1)


def pc(v, dp=0):
    return f"{v * 100:.{dp}f}%"


def main():
    arms = {"foil": load("_title_cross_foil"), "title": load("_title_cross"),
            "short": load("_short_cross"), "desc": load("")}
    nomask = load("_nomask")
    within = {"short": load("_short_within"), "desc": load("_description_within")}
    faith = json.loads((ANALYSIS / "description_faithfulness.json").read_text())
    link = json.loads((ANALYSIS / "description_link_analysis.json").read_text())

    # ---- ladder tables -------------------------------------------------
    ladder = {}
    for method in ("abc", "codegen"):
        maps = {a: acc_map(r, method) for a, r in arms.items()}
        maps["nomask"] = acc_map(nomask, method)
        rows = []
        for j in JUDGES:
            rows.append((j, [maps[a].get(j) for a in
                             ("foil", "title", "short", "desc", "nomask")]))
        rows.append(("pooled", [pooled(arms["foil"], method),
                                pooled(arms["title"], method),
                                pooled(arms["short"], method),
                                pooled(arms["desc"], method),
                                pooled(nomask, method)]))
        ladder[method] = rows

    win = {}
    for method in ("abc", "codegen"):
        s, d = acc_map(within["short"], method), acc_map(within["desc"], method)
        rows = [(j, s.get(j), d.get(j)) for j in JUDGES]
        rows.append(("pooled", pooled(within["short"], method),
                     pooled(within["desc"], method)))
        win[method] = rows

    did = {}
    for name in ("short", "desc"):
        did[name] = did_rows(cells_of(within[name]))

    # ---- faithfulness quick table --------------------------------------
    def facc(mode, key):
        v = faith["per_mode"][mode]["accuracy"].get(key)
        return f"{pc(v['acc'])} <span class=sd>(n={v['n']})</span>" if v else "—"

    faith_rows = [
        ("key (tonic)", facc("abc", "key_tonic"), facc("codegen", "key_tonic")),
        ("key (mode)", facc("abc", "key_mode"), facc("codegen", "key_mode")),
        ("tempo (bpm)", facc("abc", "tempo_bpm"), facc("codegen", "tempo_bpm")),
        ("texture", facc("abc", "texture"), facc("codegen", "texture")),
        ("dynamics claimed &amp; present", facc("abc", "dynamics"),
         facc("codegen", "dynamics")),
    ]

    # ---- render --------------------------------------------------------
    def ladder_table(method):
        chance = 1 / 11
        h = [f"<h4>{method}</h4><div class=tscroll><table>"]
        h.append("<tr><th>judge</th><th class=tip data-tip='Same puzzles, but "
                 "each text is swapped for one from a DIFFERENT piece by the "
                 "same composer — whatever accuracy survives is pure "
                 "composer-style routing.'>foil</th><th>title</th>"
                 "<th>short</th><th>full desc</th>"
                 "<th class=tip data-tip='Full descriptions with key/tempo/"
                 "meter/instrument mentions left unmasked — the header-lookup "
                 "ceiling.'>unmasked</th></tr>")
        for j, vals in ladder[method]:
            cls = " class=ref" if j == "pooled" else ""
            cells = "".join(
                f"<td>{pc(v, 1) if v is not None else '—'}</td>" for v in vals)
            h.append(f"<tr{cls}><td class=m>{j}</td>{cells}</tr>")
        h.append("</table></div>")
        h.append(f"<p class=scope>chance {pc(chance, 1)} (11-way, one piece "
                 "per composer per puzzle; 60 puzzles &times; 11 judges per "
                 "cell).</p>")
        return "\n".join(h)

    def within_table(method):
        h = [f"<h4>{method}</h4><div class=tscroll><table>"]
        h.append("<tr><th>judge</th><th>short</th><th>full desc</th></tr>")
        for j, s, d in win[method]:
            cls = " class=ref" if j == "pooled" else ""
            h.append(f"<tr{cls}><td class=m>{j}</td>"
                     f"<td>{pc(s,1) if s is not None else '—'}</td>"
                     f"<td>{pc(d,1) if d is not None else '—'}</td></tr>")
        h.append("</table></div>")
        return "\n".join(h)

    def did_table(name, label):
        rows, obs, p = did[name]
        h = [f"<h4>{label} <span class=sub>mean DiD {obs*100:+.1f}pp, "
             f"permutation p = {p:.3f}</span></h4><div class=tscroll><table>"]
        h.append("<tr><th>composer = judge</th><th>own puzzles</th>"
                 "<th>其 others’ puzzles</th><th>peers on its puzzles</th>"
                 "<th>peers elsewhere</th><th>DiD</th></tr>")
        for C, (a, b, c, d, v) in sorted(rows.items(), key=lambda kv: -kv[1][4]):
            h.append(f"<tr><td class=m>{C}</td><td>{pc(a,1)}</td>"
                     f"<td>{pc(b,1)}</td><td>{pc(c,1)}</td><td>{pc(d,1)}</td>"
                     f"<td><b>{v*100:+.1f}pp</b></td></tr>")
        h.append("</table></div>")
        return "\n".join(h).replace("其 ", "")  # guard against stray chars

    C = link["C_persuasion"]
    E = link["E_fingerprint"]
    text_fp = max(v for k, v in E["abc"].items() if k.startswith("text_loo_acc"))
    text_fp_cg = max(v for k, v in E["codegen"].items()
                     if k.startswith("text_loo_acc"))

    fragment = f"""{MARK_BEGIN}
<style>
  .cols {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1.4rem; }}
  @media (max-width: 760px) {{ .cols {{ grid-template-columns: 1fr; }} }}
</style>
  <h2>Matching: can a judge pair each text with its piece?</h2>
  <p class="scope">A separate experiment on the June free-form corpus (11
  composers &times; 30 samples &times; abc/codegen, 645 pieces; en-route
  descriptions only). Judges receive N blind score representations and N texts
  in scrambled order and must return the one-to-one pairing (11 LLM judges,
  every puzzle). Technical identifiers printed in the score header (key, tempo,
  meter, instruments, voice counts) are masked out of the texts, so matching has
  to run on musical content.</p>

  <h3>Claims vs measurements</h3>
  <p>Structured claims were LLM-extracted from all 651 descriptions and checked
  against computed features. Descriptions are faithful to whatever the
  <em>notation format</em> could express, and silently wrong wherever the
  pipeline dropped the plan:</p>
  <div class=tscroll><table>
  <tr><th>claim</th><th>abc</th><th>codegen</th></tr>
  {''.join(f'<tr><td class=m>{k}</td><td>{a}</td><td>{c}</td></tr>' for k, a, c in faith_rows)}
  </table></div>
  <p class=scope>Tempo collapses in codegen because 286/321 codegen scores set no
  tempo mark and render at the 120&nbsp;bpm default; dynamics are the mirror
  image (claimed swells are notated in codegen, almost never in abc).</p>

  <h3>The informativeness ladder (cross-composer)</h3>
  <p>How many words does it take to identify a piece among 11 candidates?
  The <b>foil</b> arm is the control: same puzzles, but each text comes from a
  <em>different</em> piece by the same composer — so its accuracy is the
  composer-style channel alone, and anything above it is piece content.</p>
  <div class=cols>
  <div>{ladder_table('abc')}</div>
  <div>{ladder_table('codegen')}</div>
  </div>
  <div class=callout>Titles are nearly pure style perfume: ~4pp of content over
  the foil floor. One masked sentence triples the signal; the full description
  reaches {pc(pooled(arms['desc'],'abc'))}/{pc(pooled(arms['desc'],'codegen'))}
  pooled. The unmasked column shows header lookup is a crutch only weak judges
  need — frontier judges gain &le;2pp from it.</div>

  <h3>Within-composer matching (style can&rsquo;t help)</h3>
  <p>Each composer&rsquo;s pieces are split into 10-way puzzles (chance 10%);
  every judge solves every composer&rsquo;s puzzles. Style routing is useless
  here — only piece-specific content works.</p>
  <div class=cols>
  <div>{within_table('abc')}</div>
  <div>{within_table('codegen')}</div>
  </div>
  <p class=scope>The full-description advantage over the one-sentence summary is
  about as large within-composer as cross-composer (codegen: +{(pooled(within['desc'],'codegen')-pooled(within['short'],'codegen'))*100:.0f}pp vs
  +{(pooled(arms['desc'],'codegen')-pooled(arms['short'],'codegen'))*100:.0f}pp) — long descriptions win on genuine
  musical content, not incidental identifying detail.</p>

  <h3>Self-recognition</h3>
  <p>Does a model recognize <em>its own</em> pieces? The 11&times;11
  judge&times;composer matrix supports a difference-in-differences: a judge&rsquo;s
  accuracy on its own puzzles, relative to its accuracy elsewhere, relative to
  how much every other judge drops on those same puzzles. This controls both
  judge ability and puzzle difficulty; the permutation test shuffles which judge
  plays &ldquo;author&rdquo;.</p>
  {did_table('desc', 'Full descriptions')}
  {did_table('short', 'One-sentence summaries')}
  <div class=callout>With full descriptions, self-recognition is real
  (+{did['desc'][1]*100:.1f}pp, p&nbsp;=&nbsp;{did['desc'][2]:.3f}) and concentrates in the
  homogeneous-corpus composers — when all ten candidates sound alike, only
  author-side knowledge breaks ties. At summary granularity the effect vanishes
  (+{did['short'][1]*100:.1f}pp, p&nbsp;=&nbsp;{did['short'][2]:.2f}): whatever privileged
  information a model has about its own pieces, one sentence can&rsquo;t carry it.</div>

  <h3>Related results from the same corpus</h3>
  <p class=scope>
  Composers are identifiable from a single description embedding at
  {pc(text_fp)}/{pc(text_fp_cg)} (abc/codegen, chance 9%) — a stronger authorship
  signature than the audio itself (~42%). Showing the composer&rsquo;s note to
  judges shifts scores by {C['mean_delta_noted_minus_blind']:+.2f} on a 1&ndash;5 scale on average, but the
  shift correlates &rho;&nbsp;=&nbsp;{C['intent_vs_delta'][0]:.2f} with the intent-execution score:
  notes amplify faithful describers and penalize overclaimers. Full numbers in
  <code>docs/analysis/description_link_analysis.json</code>.</p>

  <p class=scope><b>Caveats.</b> 6 degenerate codegen pieces were retroactively
  excluded; the July full-description runs predate that fix and include them.
  Those runs also carry a small since-fixed mask leak (hyphenated
  &ldquo;minor-key&rdquo;, standalone modal names; 125/645 pieces) — the
  unmasked-ceiling result bounds its impact, since strong judges were at ceiling
  with no masking at all. Foil accuracy is slightly inflated by piece-population
  priors, making the content estimates conservative.</p>
{MARK_END}"""

    doc = OUT.read_text(encoding="utf-8")
    if MARK_BEGIN in doc and MARK_END in doc:
        pre = doc.split(MARK_BEGIN)[0]
        post = doc.split(MARK_END)[1]
        doc = pre + fragment + post
    else:
        anchor = "<h2 id='footnotes'>"
        assert anchor in doc, "multimodal.html: no insertion anchor found"
        doc = doc.replace(anchor, fragment + "\n\n" + anchor, 1)
    OUT.write_text(doc, encoding="utf-8")
    print(f"Spliced matching-program section into {OUT} "
          f"({len(fragment)} chars)")
    print(f"  desc DiD {did['desc'][1]*100:+.1f}pp p={did['desc'][2]:.4f}; "
          f"short DiD {did['short'][1]*100:+.1f}pp p={did['short'][2]:.4f}")


if __name__ == "__main__":
    main()
